---
title: "Visuals of non-NEON data"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
data_dir <- "/nfs/public-data/NEON_workshop_data/NEON"

# read in data
ACS <- readr::read_csv(file.path(data_dir, "NEON_AOP_ACS.csv"), col_types = "nccnccccccccc") # ACS data
# ACS <- readr::read_csv("NEON_AOP_ACS.csv", col_types = "nccnccccccccc") # ACS data
NLCD <- readr::read_csv(file.path(data_dir, "NEON-AOP-LandCover.csv"), col_types = "cccccccccccccccccccc") # NLCD data
# NASS <-  # NASS data

```

```{r ACS subsetting, include=FALSE}
# Function to sub-set ACS dataframe by variables for plotting ease
sub_acs <- function(df, var, newcol){
           sub <- df %>% 
                  filter(description == var) %>% 
                  group_by(Site) %>% 
                  mutate({{newcol}} :=  mean(estimate)) %>% 
                  ungroup() %>% 
                  distinct(Site, {{newcol}})
           return(sub)
           }

# population
pop <- sub_acs(ACS, "Population", mean_pop)

# employed
emp <- sub_acs(ACS, "Employed", mean_employed)

```


```{r plot function, include=FALSE}
plot_var <- function(dat, x, y){
            p <- ggplot(data = dat, aes(x = {{x}}, y = {{y}})) +
                 geom_col() + 
                 theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
            return(p)
}
```

```{r plots}
# population
plot_var(pop, Site, mean_pop)

# employed
plot_var(emp, Site, mean_employed)

# developed land
plot_var(NLCD, Site, all_developed)

```